---
title: "Climate model_demo"
author: Pat Byrne, Evan Heberlein, Ruben Sanchez Ramirez
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackages}
library(lubridate)
library(ggplot2)
library(tidyverse)
library(chron)
library(ncdf4)
library(RColorBrewer)
library(lattice)
library(patchwork)
```

## Reading in the data
```{r helpfulfunctions_data}
create_nc_ensemble_dataarray <- function(nc_string_in, var_name){
  ncin <- nc_open(nc_string_in)
  
  lon <- ncvar_get(ncin,"lon")
  lat <- ncvar_get(ncin,"lat")
  
  lats=which(lat >= 37 & lat <= 42)
  lons=which(lon >= 235 & lon <= 240)
  
  var_data_array <- ncvar_get(ncin, 
                              var_name, 
                              start=c(min(lons), min(lats), 1), 
                              count=c(length(lons), length(lats), -1)
                              )
  return(var_data_array)
}

get_ensemble_rtime <- function(nc_string_in){
  ncin <- nc_open(nc_string_in)
  
  time <- ncvar_get(ncin,"time")
  tunits <- ncatt_get(ncin,"time","units")
  
  tustr <- strsplit(tunits$value, " ")
  tdstr <- strsplit(unlist(tustr)[3], "-")
  tmonth <- as.integer(unlist(tdstr)[2])
  tday <- as.integer(unlist(tdstr)[3])
  tyear <- as.integer(unlist(tdstr)[1])
  rtime <- chron(time,origin=c(tmonth, tday, tyear))
  return(rtime)
}

```
```{r mintempdata}
# This chunk creates three arrays of monthly average rural daily minimum temperature (degrees C)
filename1 <- "climdata/b.e11.BRCP85C5CNBDRD.f09_g16.001.clm2.h0.TREFMNAV_R.200601-208012.nc"
filename2 <- "climdata/b.e11.BRCP85C5CNBDRD.f09_g16.002.clm2.h0.TREFMNAV_R.200601-208012.nc"
filename3 <- "climdata/b.e11.BRCP85C5CNBDRD.f09_g16.003.clm2.h0.TREFMNAV_R.200601-208012.nc"
dname <- "TREFMNAV_R"

monavg_mindailyT_ens1 <- create_nc_ensemble_dataarray(nc_string_in = filename1, 
                                                      var_name = dname) - 273.15

monavg_mindailyT_ens2 <- create_nc_ensemble_dataarray(nc_string_in = filename2, 
                                                      var_name = dname) - 273.15

monavg_mindailyT_ens3 <- create_nc_ensemble_dataarray(nc_string_in = filename3, 
                                                      var_name = dname) - 273.15
```
```{r rainfalldata}
# This chunk creates three arrays of monthly average rainfall (mm/s)
filename1 <- "climdata/b.e11.BRCP85C5CNBDRD.f09_g16.005.clm2.h0.RAIN.200601-208012.nc"
filename2 <- "climdata/b.e11.BRCP85C5CNBDRD.f09_g16.006.clm2.h0.RAIN.200601-208012.nc"
filename3 <- "climdata/b.e11.BRCP85C5CNBDRD.f09_g16.007.clm2.h0.RAIN.200601-208012.nc"
dname <- "RAIN"

monavg_meanrain_ens1 <- create_nc_ensemble_dataarray(nc_string_in = filename1, 
                                                      var_name = dname) 

monavg_meanrain_ens2 <- create_nc_ensemble_dataarray(nc_string_in = filename2, 
                                                      var_name = dname) 

monavg_meanrain_ens3 <- create_nc_ensemble_dataarray(nc_string_in = filename3, 
                                                      var_name = dname) 
```

## Manipulating data for workability
```{r}
# Composite array of monthly average rural daily minimum temp (degrees C)
minT_composite <- (monavg_mindailyT_ens1 + monavg_mindailyT_ens2 + monavg_mindailyT_ens3)/3

# Composite array of monthly average rainfall (mm/s)
rainfall_composite <- (monavg_meanrain_ens1 + monavg_meanrain_ens2 + monavg_meanrain_ens3)/3
```


```{r timevector}
# Generating a vector of dates that are index-matched to the time dimension (length 900) in the climate data arrays
# This was necessary because there are issues with just retrieving the time dimension like Sam did in her example code (I think there are errors in her code that she missed)
time1 <-get_ensemble_rtime(filename3)
timeseq <- seq(time1[1]-31, to = time1[length(time1)], by = 'month')
length(timeseq) # Must be the same length as the time dimension in the composite arrays (900)!

monseq <- month(timeseq)

Jan_indxs <- which(monseq == 1)
Apr_indxs <- which(monseq == 4)
Jun_indxs <- which(monseq == 6)
Jul_indxs <- which(monseq == 7)
Sep_indxs <- which(monseq == 9)
Oct_indxs <- which(monseq == 10)

jan_ids <- Jan_indxs[2:length(Jan_indxs)] # Time dimension month indices for January 2007-2080
apr_ids <- Apr_indxs[2:length(Apr_indxs)] # Time dimension month indices for April 2007-2080
jun_ids <- Jun_indxs[2:length(Jun_indxs)] # Time dimension month indices for June 2007-2080
jul_ids <- Jul_indxs[2:length(Jul_indxs)] # Time dimension month indices for July 2007-2080
prev_sep_ids <- Sep_indxs[1:(length(Sep_indxs)-1)] # Time dimension month indices for September 2006-2079
prev_oct_ids <- Oct_indxs[1:(length(Oct_indxs)-1)] # Time dimension month indices for October 2006-2079

# Total seconds in a 31-day month (Jan, Oct): 2678400
# Total seconds in a 30-day month (Jun, Sep): 2592000
```

```{r createarrays}
apr_minT <- minT_composite[,,apr_ids] # Array of gridded mean minimum daily temp (C) in April
jul_minT <- minT_composite[,,jul_ids] # Array of gridded mean minimum daily temp (C) in July

jan_prcp <- rainfall_composite[,,jan_ids]*2678400 # Array of gridded total precip (mm) in January
jun_prcp <- rainfall_composite[,,jun_ids]*2592000 # Array of gridded total precip (mm) in June

prevsep_prcp <- rainfall_composite[,,prev_sep_ids]*2592000 # Array of gridded total precip (mm) in previous September
prevoct_prcp <- rainfall_composite[,,prev_oct_ids]*2678400 # Array of gridded total precip (mm) in previous October
```


### Define empirical model equations

```{r}
# A function to calculate yield anomaly (tons/acre deviation from historical average yield) for WINE grapes
# Numeric inputs are average minimum daily temperature (C) in April for the year in question, total precipitation (mm) in June for the year in question, and total precipitation in September in the previous year
# Equation based on Lobell et al 2006
wine_anomaly <- function(apr_minT, jun_prcp, prevSept_prcp){
  yanom <- 2.65*apr_minT - 0.17*(apr_minT^2) + 4.78*jun_prcp - 4.93*(jun_prcp^2) - 2.24*prevSept_prcp + 1.54*(prevSept_prcp^2) - 10.5
  return(yanom)
}

wine_yield <- function(apr_minT, jun_prcp, prevSept_prcp){
  yanom <- 2.65*apr_minT - 0.17*(apr_minT^2) + 4.78*jun_prcp - 4.93*(jun_prcp^2) - 2.24*prevSept_prcp + 1.54*(prevSept_prcp^2) - 10.5
  hist_mean <- 7
  yield <- yanom + hist_mean
  if (yield < 0) {yield = 0}
  return(yield)
}

# A function to calculate yield anomaly (tons/acre deviation from historical average yield) for TABLE grapes
# Numeric inputs are average minimum daily temperature (C) in July for the year in question, average minimum daily temperature (C) in April for the year in question, total precipitation (mm) in January for the year in question, and total precipitation (mm) in October in the previous year
# Equation based on Lobell et al 2006
table_anomaly <- function(jul_minT, apr_minT, jan_prcp, prevOct_prcp){
  yanom <- 6.93*jul_minT - 0.19*jul_minT^2 + 2.61*apr_minT - 0.15*apr_minT^2 + 0.035*jan_prcp + 0.024*jan_prcp^2 + 1.71*prevOct_prcp - 0.673*prevOct_prcp - 73.89
  return(yanom)
}

table_yield <- function(jul_minT, apr_minT, jan_prcp, prevOct_prcp){
  yanom <- 6.93*jul_minT - 0.19*jul_minT^2 + 2.61*apr_minT - 0.15*apr_minT^2 + 0.035*jan_prcp + 0.024*jan_prcp^2 + 1.71*prevOct_prcp - 0.673*prevOct_prcp - 73.89
  hist_mean <- 12
  yield <- yanom + hist_mean
  if (yield < 0) {yield = 0}
  return(yield)
}
```

### Implement the model
```{r}
wine_array <- array(0, c(5,6,74))
table_array <- array(0, c(5,6,74))

for (i in 1:74) {
  for (j in 1:5) {
    for (k in 1:6) {
      wine_array[j,k,i] = wine_anomaly(apr_minT = apr_minT[j,k,i],
                                       jun_prcp = jun_prcp[j,k,i],
                                       prevSept_prcp = prevsep_prcp[j,k,i])
      table_array[j,k,i] = table_anomaly(jul_minT = jul_minT[j,k,i],
                                       apr_minT = apr_minT[j,k,i],
                                       jan_prcp = jan_prcp[j,k,i],
                                       prevOct_prcp = prevoct_prcp[j,k,i])
    }
  }
}

# Calculate averages for each year (across all lats/longs)

wine_avg <- c()
table_avg <- c()

for (i in 1:74) {
  wine_avg[i] = mean(wine_array[,,i], na.rm = TRUE)
  table_avg[i] = mean(table_array[,,i], na.rm = TRUE)
}


# Scaling relative to min (for negative vals)/max (for positive vals)
wine_scaled <- c()
table_scaled <- c()

for (i in 1:74) {
  wine_scaled[i] = wine_avg[i]/min(wine_avg)
  table_scaled[i] = table_avg[i]/max(table_avg)
}


# Convert to data frame to line up with years
wine_df <- as_data_frame(wine_scaled) %>% 
  add_column(year = 2007:2080)

table_df <- as_data_frame(table_scaled) %>% 
  add_column(year = 2007:2080)
```

# Create figures
```{r}
wine_graph <- ggplot(data = wine_df) + 
  geom_line(aes(x = year, y = value)) +
  ggtitle("Scaled yield anomaly for wine grapes in Northern California: 2007-2080",
          subtitle = "Scaling relative to minimum yield anomaly of -21659.58 tons/acre") +
  labs(x = "Year",
       y = "|Scaled yield anomaly|") +
  theme_minimal() +
  scale_y_continuous(expand = (c(0,0)))

table_graph <- ggplot(data = table_df) + 
  geom_line(aes(x = year, y = value)) +
  ggtitle("Scaled yield anomaly for table grapes in Northern California: 2007-2080",
          subtitle = "Scaling relative to maximum yield anomaly of 4376.45 tons/acre") +
  labs(x = "Year",
       y = "Scaled yield anomaly") +
  theme_minimal() +
  scale_y_continuous(expand = (c(0,0)))

(wine_graph / table_graph)
```

